name: maitri_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.8.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  api_repository:
    path: packages/api_repository
  l10m: ^0.4.3
  path_provider: ^2.1.5
  hydrated_bloc: ^9.1.5

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
