name: supabase_auth_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  token_storage:
    path: ../token_storage
  authenctication_client:
    path: ../authenctication_client
  powersync_repository:
    path: ../../powersync_repository
  supabase_flutter: ^2.0.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
