name: powersync_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  shared:
    path: ../shared
  flutter:
    sdk: flutter
  path: ">=1.8.3 <=1.9.0"
  powersync: ^1.10.0
  supabase_flutter: ^2.8.2
  firebase_auth_platform_interface: ^7.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
